
# SEO settings
title: "John"
title2: " Amata" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: "" # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/jpamata/jpamata.github.io
disqus_shortname: "john-amata"
twitter_username: "john__amata"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "John"
  job      : "very ordinary guy."
  bio      : ""
  thumb    : /images/johnamata.jpg
  email    : johnamata@gmx.com
  url      : http://jpamata.github.io
  github   : https://github.com/jpamata
  twitter  : https://twitter.com/john__amata
  facebook : https://www.facebook.com/JohnTheGreat
  linkedin : https://linkedin.com/in/jpamata

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@john__amata"

gems:
  - bourbon
  - jekyll-paginate
  - jekyll-seo-tag

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : contact
    title: Contact

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
