name: John Patrick Amata
description: >
    John Patrick Amata
about: >
    A little bit of everything.
baseurl: "/"  
url: "http://johnamata.com"
markdown: kramdown
excerpt_separator: "<!-- more -->"
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 5

logo: "/assets/jpalogo.png"
disqus_shortname: 

# john-amata

rtl: false
owner:
  name:           jpa
  avatar:         "/assets/jpalogo.png"
  twitter: https://twitter.com/john__amata
  email:          
  # Social networking links used in footer. Update and remove as you like.
  github: 
  stackexchange: 
  linkedin: https://www.linkedin.com/in/jpamata
  facebook: https://www.facebook.com/JohnTheGreat
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: 'UA-107698218-1'
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
