
# SEO settings
title: "John"
title2: " Amata" # default: ""
description: "Just another minimalist Jekyll theme for technical writing."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: "" # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/jpamata/jpamata.github.io
disqus_shortname: "john_amata"
twitter_username: "john__amata"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "John"
  job      : "blogger, programmer, and massive bibliophile."
  bio      : "I’ll be writing my adventures and exploits, random thoughts and musings, and the projects I’ll be doing and be part of along the way. I hope that this journal will help me guide myself on this wide, long, space called life. Take what you need, and pass it on."
  thumb    : /images/author.jpg
  email    : hnrird@gmail.com
  url      : http://heiswayi.github.io
  github   : http://github.com/heiswayi
  twitter  : http://twitter.com/HeiswayiNrird
  facebook : https://www.facebook.com/heiswayi.nrird
  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
