name: John Patrick Amata
description: >
    Writings on Software
about: >

baseurl: "/"  
url: johnamata.com
markdown: kramdown
excerpt_separator: "<!-- more -->"
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 5

logo: "/assets/jpalogo.png"
disqus_shortname: john-amata

rtl: false
owner:
  name:           jpa
  avatar:         "/assets/jpalogo.png"
  twitter: https://twitter.com/john__amata
  email:          "hello@johnamata.com"
  # Social networking links used in footer. Update and remove as you like.
  github: https://github.com/jpamata
  stackexchange: https://stackoverflow.com/users/8152343/jpamata
  linkedin: https://www.linkedin.com/in/jpamata
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: 'UA-107698218-1'
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: